services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - OCTANE_SERVER=swoole
      - OCTANE_HTTPS=false
      # JUST FOR TEST!!! Delete APP_KEY in production mode!
      - APP_KEY=base64:9BpTbiYHijYixU6CGgEOa5tFfCOxFfdn2/o72ZfAixY=
      - LOG_LEVEL=error
      - DB_CONNECTION=pgsql
      - DB_HOST=laravel_postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - REDIS_HOST=laravel_redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=null
      - CACHE_STORE=redis
      - SESSION_DRIVER=database
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - laravel

  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  postgres:
    driver: local

networks:
  laravel:
    driver: bridge
